Import-Module ActiveDirectory -ErrorAction Stop

$LabRoot = "C:\IT-Automation-Lab"
$ReportFile = "$LabRoot\Reports\IT-Automation-Lab-Summary.html"

$AllUsers = Get-ADUser -Filter * -Properties Enabled
$EnabledUsers = $AllUsers | Where-Object Enabled -eq $true
$DisabledUsers = $AllUsers | Where-Object Enabled -eq $false
$Groups = Get-ADGroup -Filter *
$OrganizationalUnits = Get-ADOrganizationalUnit -Filter *
$Scripts = Get-ChildItem "$LabRoot\Scripts" -Filter "*.ps1"

$BulkLogPath = "$LabRoot\Logs\Bulk-User-Creation-Log.csv"
$PasswordLogPath = "$LabRoot\Logs\Password-Reset-Log.csv"
$OffboardingLogPath = "$LabRoot\Logs\Offboarding-Log.csv"

$BulkLog = if (Test-Path $BulkLogPath) {
    Import-Csv $BulkLogPath
}
else {
    @()
}

$PasswordLog = if (Test-Path $PasswordLogPath) {
    Import-Csv $PasswordLogPath
}
else {
    @()
}

$OffboardingLog = if (Test-Path $OffboardingLogPath) {
    Import-Csv $OffboardingLogPath
}
else {
    @()
}

$BulkTable = $BulkLog |
    Select-Object Username,Department,Group,Status |
    ConvertTo-Html -Fragment

$PasswordTable = $PasswordLog |
    Select-Object Timestamp,Technician,Username,Action,Status |
    ConvertTo-Html -Fragment

$OffboardingTable = $OffboardingLog |
    Select-Object Timestamp,Technician,Username,RemovedGroups,Status |
    ConvertTo-Html -Fragment

$ScriptTable = $Scripts |
    Select-Object Name,Length,LastWriteTime |
    ConvertTo-Html -Fragment

$Domain = (Get-ADDomain).DNSRoot
$GeneratedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$Html = @"
<!DOCTYPE html>
<html>
<head>
    <title>IT Automation Lab Summary</title>
    <style>
        body {
            font-family: Segoe UI, Arial, sans-serif;
            margin: 40px;
            background-color: #f4f6f8;
            color: #1f2937;
        }

        h1 {
            color: #123b63;
            margin-bottom: 5px;
        }

        h2 {
            color: #185a8d;
            border-bottom: 2px solid #d1d5db;
            padding-bottom: 6px;
            margin-top: 35px;
        }

        .subtitle {
            color: #52606d;
            margin-bottom: 25px;
        }

        .cards {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
        }

        .card {
            background: white;
            border-left: 5px solid #0078d4;
            padding: 18px;
            width: 190px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.10);
        }

        .number {
            font-size: 30px;
            font-weight: bold;
            color: #123b63;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            background: white;
            margin-top: 10px;
        }

        th {
            background-color: #123b63;
            color: white;
            text-align: left;
            padding: 10px;
        }

        td {
            border-bottom: 1px solid #d1d5db;
            padding: 9px;
        }

        tr:nth-child(even) {
            background-color: #f3f4f6;
        }

        .footer {
            margin-top: 40px;
            color: #6b7280;
            font-size: 13px;
        }
    </style>
</head>

<body>
    <h1>PowerShell IT Support Automation Lab</h1>
    <div class="subtitle">
        Domain: $Domain | Generated: $GeneratedAt
    </div>

    <h2>Active Directory Overview</h2>

    <div class="cards">
        <div class="card">
            <div class="number">$($AllUsers.Count)</div>
            Total Users
        </div>

        <div class="card">
            <div class="number">$($EnabledUsers.Count)</div>
            Enabled Users
        </div>

        <div class="card">
            <div class="number">$($DisabledUsers.Count)</div>
            Disabled Users
        </div>

        <div class="card">
            <div class="number">$($Groups.Count)</div>
            Security Groups
        </div>

        <div class="card">
            <div class="number">$($OrganizationalUnits.Count)</div>
            Organizational Units
        </div>

        <div class="card">
            <div class="number">$($Scripts.Count)</div>
            Automation Scripts
        </div>
    </div>

    <h2>Bulk User Provisioning</h2>
    $BulkTable

    <h2>Password Reset Operations</h2>
    $PasswordTable

    <h2>Offboarding Operations</h2>
    $OffboardingTable

    <h2>PowerShell Scripts</h2>
    $ScriptTable

    <div class="footer">
        Generated by $env:USERNAME on $env:COMPUTERNAME
    </div>
</body>
</html>
"@

$Html | Out-File $ReportFile -Encoding UTF8

Write-Host "`nAUTOMATION LAB REPORT GENERATED" -ForegroundColor Green
Write-Host "Report: $ReportFile"

Start-Process $ReportFile